import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Note',
  // description: "Generated by create next app",
};
const Notes = () => {
  return <div>Notes</div>;
};

export default Notes;
