import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Profile',
  // description: "Generated by create next app",
};

const Profile = () => {
  return <div>Profile</div>;
};

export default Profile;
